"""Initial tables

Revision ID: a3c361765e69
Revises: 
Create Date: 2026-06-27 15:18:43.735164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3c361765e69'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('log_id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('actor_id', sa.String(length=50), nullable=False),
    sa.Column('actor_type', sa.String(length=20), nullable=False),
    sa.Column('actor_ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('performed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('citizens',
    sa.Column('citizen_id', sa.String(length=36), nullable=False),
    sa.Column('aadhaar_hash', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('father_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('religion', sa.String(length=50), nullable=True),
    sa.Column('caste_category', sa.String(length=20), nullable=True),
    sa.Column('sub_caste', sa.String(length=50), nullable=True),
    sa.Column('phone_primary', sa.String(length=20), nullable=False),
    sa.Column('phone_secondary', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('epic_number', sa.String(length=50), nullable=True),
    sa.Column('marital_status', sa.String(length=20), nullable=True),
    sa.Column('blood_group', sa.String(length=5), nullable=True),
    sa.Column('profile_photo_url', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('session_token', sa.String(length=255), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('citizen_id')
    )
    op.create_index(op.f('ix_citizens_aadhaar_hash'), 'citizens', ['aadhaar_hash'], unique=True)
    op.create_table('notifications',
    sa.Column('notification_id', sa.String(length=36), nullable=False),
    sa.Column('recipient_id', sa.String(length=36), nullable=False),
    sa.Column('recipient_type', sa.String(length=20), nullable=False),
    sa.Column('application_id', sa.String(length=50), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('message_body', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('is_sent', sa.Boolean(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_table('offices',
    sa.Column('office_id', sa.String(length=36), nullable=False),
    sa.Column('office_code', sa.String(length=50), nullable=False),
    sa.Column('office_name', sa.String(length=100), nullable=False),
    sa.Column('office_type', sa.String(length=50), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('sub_division', sa.String(length=100), nullable=True),
    sa.Column('full_address', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('parent_office_id', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_office_id'], ['offices.office_id'], ),
    sa.PrimaryKeyConstraint('office_id')
    )
    op.create_index(op.f('ix_offices_office_code'), 'offices', ['office_code'], unique=True)
    op.create_table('roles',
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('role_code', sa.String(length=50), nullable=False),
    sa.Column('role_name', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=50), nullable=False),
    sa.Column('authority_level', sa.Integer(), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.create_index(op.f('ix_roles_role_code'), 'roles', ['role_code'], unique=True)
    op.create_table('service_catalog',
    sa.Column('service_id', sa.String(length=36), nullable=False),
    sa.Column('service_code', sa.String(length=50), nullable=False),
    sa.Column('service_name', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('required_fields_schema', sa.JSON(), nullable=False),
    sa.Column('required_documents_schema', sa.JSON(), nullable=False),
    sa.Column('max_file_size_kb', sa.Integer(), nullable=True),
    sa.Column('fee_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('expected_processing_days', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('service_id')
    )
    op.create_index(op.f('ix_service_catalog_service_code'), 'service_catalog', ['service_code'], unique=True)
    op.create_table('applications',
    sa.Column('application_id', sa.String(length=50), nullable=False),
    sa.Column('citizen_id', sa.String(length=36), nullable=False),
    sa.Column('service_id', sa.String(length=36), nullable=False),
    sa.Column('processing_office_id', sa.String(length=36), nullable=False),
    sa.Column('current_status', sa.String(length=50), nullable=True),
    sa.Column('form_data', sa.JSON(), nullable=False),
    sa.Column('purpose', sa.String(length=255), nullable=True),
    sa.Column('declaration_accepted', sa.Boolean(), nullable=True),
    sa.Column('rejection_reason', sa.String(length=255), nullable=True),
    sa.Column('return_reason', sa.String(length=255), nullable=True),
    sa.Column('priority_level', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('last_status_change_at', sa.DateTime(), nullable=True),
    sa.Column('expected_completion_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['citizen_id'], ['citizens.citizen_id'], ),
    sa.ForeignKeyConstraint(['processing_office_id'], ['offices.office_id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service_catalog.service_id'], ),
    sa.PrimaryKeyConstraint('application_id')
    )
    op.create_table('citizen_addresses',
    sa.Column('address_id', sa.String(length=36), nullable=False),
    sa.Column('citizen_id', sa.String(length=36), nullable=False),
    sa.Column('address_type', sa.String(length=20), nullable=False),
    sa.Column('house_no', sa.String(length=100), nullable=True),
    sa.Column('street_locality', sa.String(length=150), nullable=True),
    sa.Column('village_town', sa.String(length=100), nullable=False),
    sa.Column('post_office', sa.String(length=100), nullable=False),
    sa.Column('police_station', sa.String(length=100), nullable=False),
    sa.Column('circle', sa.String(length=100), nullable=True),
    sa.Column('sub_division', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('pin_code', sa.String(length=10), nullable=False),
    sa.Column('area_type', sa.String(length=10), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['citizen_id'], ['citizens.citizen_id'], ),
    sa.PrimaryKeyConstraint('address_id')
    )
    op.create_table('citizen_education',
    sa.Column('education_id', sa.String(length=36), nullable=False),
    sa.Column('citizen_id', sa.String(length=36), nullable=False),
    sa.Column('exam_passed', sa.String(length=100), nullable=False),
    sa.Column('board_or_university', sa.String(length=150), nullable=False),
    sa.Column('institute_name', sa.String(length=150), nullable=False),
    sa.Column('subjects_list', sa.String(length=255), nullable=False),
    sa.Column('division_or_grade', sa.String(length=50), nullable=False),
    sa.Column('percentage_or_cgpa', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('year_of_passing', sa.Integer(), nullable=False),
    sa.Column('course_duration_years', sa.Integer(), nullable=False),
    sa.Column('instruction_medium', sa.String(length=50), nullable=False),
    sa.Column('certificate_doc_url', sa.String(length=255), nullable=True),
    sa.Column('certificate_doc_hash', sa.String(length=64), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['citizen_id'], ['citizens.citizen_id'], ),
    sa.PrimaryKeyConstraint('education_id')
    )
    op.create_table('citizen_family_members',
    sa.Column('family_member_id', sa.String(length=36), nullable=False),
    sa.Column('citizen_id', sa.String(length=36), nullable=False),
    sa.Column('relationship', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('occupation', sa.String(length=100), nullable=True),
    sa.Column('annual_income', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_alive', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['citizen_id'], ['citizens.citizen_id'], ),
    sa.PrimaryKeyConstraint('family_member_id')
    )
    op.create_table('citizen_languages',
    sa.Column('language_id', sa.String(length=36), nullable=False),
    sa.Column('citizen_id', sa.String(length=36), nullable=False),
    sa.Column('language_name', sa.String(length=50), nullable=False),
    sa.Column('can_read', sa.Boolean(), nullable=True),
    sa.Column('can_write', sa.Boolean(), nullable=True),
    sa.Column('can_speak', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['citizen_id'], ['citizens.citizen_id'], ),
    sa.PrimaryKeyConstraint('language_id')
    )
    op.create_table('citizen_physical_standards',
    sa.Column('physical_id', sa.String(length=36), nullable=False),
    sa.Column('citizen_id', sa.String(length=36), nullable=False),
    sa.Column('height_cm', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('chest_normal_cm', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('chest_expanded_cm', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('wears_glasses', sa.Boolean(), nullable=True),
    sa.Column('disability_status', sa.String(length=20), nullable=True),
    sa.Column('disability_type', sa.String(length=100), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['citizen_id'], ['citizens.citizen_id'], ),
    sa.PrimaryKeyConstraint('physical_id')
    )
    op.create_table('citizen_work_experience',
    sa.Column('experience_id', sa.String(length=36), nullable=False),
    sa.Column('citizen_id', sa.String(length=36), nullable=False),
    sa.Column('employer_name', sa.String(length=150), nullable=False),
    sa.Column('post_held', sa.String(length=100), nullable=False),
    sa.Column('nature_of_work', sa.String(length=255), nullable=True),
    sa.Column('experience_type', sa.String(length=20), nullable=False),
    sa.Column('job_type', sa.String(length=20), nullable=False),
    sa.Column('pay_on_leaving', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('from_date', sa.Date(), nullable=False),
    sa.Column('to_date', sa.Date(), nullable=True),
    sa.Column('experience_doc_url', sa.String(length=255), nullable=True),
    sa.Column('experience_doc_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['citizen_id'], ['citizens.citizen_id'], ),
    sa.PrimaryKeyConstraint('experience_id')
    )
    op.create_table('employment_registrations',
    sa.Column('registration_id', sa.String(length=50), nullable=False),
    sa.Column('citizen_id', sa.String(length=36), nullable=False),
    sa.Column('processing_office_id', sa.String(length=36), nullable=False),
    sa.Column('current_state', sa.String(length=50), nullable=True),
    sa.Column('seniority_date', sa.Date(), nullable=False),
    sa.Column('lifespan_expiry_date', sa.Date(), nullable=False),
    sa.Column('last_renewal_date', sa.Date(), nullable=True),
    sa.Column('renewal_count', sa.Integer(), nullable=True),
    sa.Column('physical_standards_snapshot', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['citizen_id'], ['citizens.citizen_id'], ),
    sa.ForeignKeyConstraint(['processing_office_id'], ['offices.office_id'], ),
    sa.PrimaryKeyConstraint('registration_id'),
    sa.UniqueConstraint('citizen_id')
    )
    op.create_table('government_officials',
    sa.Column('official_id', sa.String(length=36), nullable=False),
    sa.Column('office_id', sa.String(length=36), nullable=False),
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.Column('designation', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('blockchain_wallet_address', sa.String(length=100), nullable=False),
    sa.Column('dsc_serial_number', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['office_id'], ['offices.office_id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ),
    sa.PrimaryKeyConstraint('official_id')
    )
    op.create_index(op.f('ix_government_officials_blockchain_wallet_address'), 'government_officials', ['blockchain_wallet_address'], unique=True)
    op.create_index(op.f('ix_government_officials_employee_id'), 'government_officials', ['employee_id'], unique=True)
    op.create_table('workflow_stages',
    sa.Column('stage_id', sa.String(length=36), nullable=False),
    sa.Column('service_id', sa.String(length=36), nullable=False),
    sa.Column('stage_order', sa.Integer(), nullable=False),
    sa.Column('stage_code', sa.String(length=50), nullable=False),
    sa.Column('stage_name', sa.String(length=100), nullable=False),
    sa.Column('required_role', sa.String(length=50), nullable=False),
    sa.Column('sla_hours', sa.Integer(), nullable=True),
    sa.Column('is_terminal', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['service_catalog.service_id'], ),
    sa.PrimaryKeyConstraint('stage_id')
    )
    op.create_table('application_assignments',
    sa.Column('assignment_id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=50), nullable=False),
    sa.Column('assigned_to', sa.String(length=36), nullable=False),
    sa.Column('assigned_by', sa.String(length=36), nullable=False),
    sa.Column('assignment_type', sa.String(length=50), nullable=True),
    sa.Column('assignment_status', sa.String(length=50), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.application_id'], ),
    sa.PrimaryKeyConstraint('assignment_id')
    )
    op.create_table('application_documents',
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=50), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('document_label', sa.String(length=100), nullable=False),
    sa.Column('original_filename', sa.String(length=150), nullable=False),
    sa.Column('storage_url', sa.String(length=255), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('verified_by', sa.String(length=36), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.application_id'], ),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_index(op.f('ix_application_documents_file_hash'), 'application_documents', ['file_hash'], unique=True)
    op.create_table('application_fees',
    sa.Column('fee_id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('transaction_reference', sa.String(length=100), nullable=True),
    sa.Column('payment_status', sa.String(length=50), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.application_id'], ),
    sa.PrimaryKeyConstraint('fee_id')
    )
    op.create_table('application_remarks',
    sa.Column('remark_id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=50), nullable=False),
    sa.Column('official_id', sa.String(length=36), nullable=False),
    sa.Column('remark_type', sa.String(length=50), nullable=False),
    sa.Column('remark_text', sa.Text(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=True),
    sa.Column('requires_citizen_response', sa.Boolean(), nullable=True),
    sa.Column('citizen_response', sa.Text(), nullable=True),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.application_id'], ),
    sa.ForeignKeyConstraint(['official_id'], ['government_officials.official_id'], ),
    sa.PrimaryKeyConstraint('remark_id')
    )
    op.create_table('application_status_logs',
    sa.Column('log_id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=50), nullable=False),
    sa.Column('from_status', sa.String(length=50), nullable=True),
    sa.Column('to_status', sa.String(length=50), nullable=False),
    sa.Column('changed_by', sa.String(length=36), nullable=False),
    sa.Column('changed_by_role', sa.String(length=50), nullable=False),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.application_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('blockchain_ledger',
    sa.Column('block_hash', sa.String(length=64), nullable=False),
    sa.Column('application_id', sa.String(length=50), nullable=False),
    sa.Column('previous_block_hash', sa.String(length=64), nullable=True),
    sa.Column('aggregate_data_hash', sa.String(length=64), nullable=False),
    sa.Column('status_at_block', sa.String(length=50), nullable=False),
    sa.Column('signee_address', sa.String(length=100), nullable=False),
    sa.Column('signee_role', sa.String(length=50), nullable=False),
    sa.Column('action_description', sa.Text(), nullable=True),
    sa.Column('block_timestamp', sa.DateTime(), nullable=True),
    sa.Column('block_sequence', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.application_id'], ),
    sa.PrimaryKeyConstraint('block_hash')
    )
    op.create_index(op.f('ix_blockchain_ledger_application_id'), 'blockchain_ledger', ['application_id'], unique=False)
    op.create_table('issued_certificates',
    sa.Column('certificate_id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=50), nullable=False),
    sa.Column('citizen_id', sa.String(length=36), nullable=False),
    sa.Column('issued_by', sa.String(length=36), nullable=False),
    sa.Column('certificate_number', sa.String(length=100), nullable=False),
    sa.Column('certificate_type', sa.String(length=50), nullable=False),
    sa.Column('certificate_hash', sa.String(length=64), nullable=False),
    sa.Column('qr_code_hash', sa.String(length=64), nullable=False),
    sa.Column('qr_code_image_url', sa.String(length=255), nullable=True),
    sa.Column('certificate_pdf_url', sa.String(length=255), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), nullable=True),
    sa.Column('revocation_reason', sa.String(length=255), nullable=True),
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.application_id'], ),
    sa.ForeignKeyConstraint(['citizen_id'], ['citizens.citizen_id'], ),
    sa.PrimaryKeyConstraint('certificate_id'),
    sa.UniqueConstraint('application_id')
    )
    op.create_index(op.f('ix_issued_certificates_certificate_number'), 'issued_certificates', ['certificate_number'], unique=True)
    op.create_table('verification_reports',
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=50), nullable=False),
    sa.Column('verifier_id', sa.String(length=36), nullable=False),
    sa.Column('verification_type', sa.String(length=50), nullable=True),
    sa.Column('verdict', sa.String(length=20), nullable=False),
    sa.Column('findings', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('verification_date', sa.Date(), nullable=False),
    sa.Column('visit_location', sa.String(length=255), nullable=True),
    sa.Column('checklist_responses', sa.JSON(), nullable=True),
    sa.Column('documents_hash_at_verification', sa.String(length=64), nullable=False),
    sa.Column('hash_match', sa.Boolean(), nullable=True),
    sa.Column('photo_evidence_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.application_id'], ),
    sa.ForeignKeyConstraint(['verifier_id'], ['government_officials.official_id'], ),
    sa.PrimaryKeyConstraint('report_id'),
    sa.UniqueConstraint('application_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verification_reports')
    op.drop_index(op.f('ix_issued_certificates_certificate_number'), table_name='issued_certificates')
    op.drop_table('issued_certificates')
    op.drop_index(op.f('ix_blockchain_ledger_application_id'), table_name='blockchain_ledger')
    op.drop_table('blockchain_ledger')
    op.drop_table('application_status_logs')
    op.drop_table('application_remarks')
    op.drop_table('application_fees')
    op.drop_index(op.f('ix_application_documents_file_hash'), table_name='application_documents')
    op.drop_table('application_documents')
    op.drop_table('application_assignments')
    op.drop_table('workflow_stages')
    op.drop_index(op.f('ix_government_officials_employee_id'), table_name='government_officials')
    op.drop_index(op.f('ix_government_officials_blockchain_wallet_address'), table_name='government_officials')
    op.drop_table('government_officials')
    op.drop_table('employment_registrations')
    op.drop_table('citizen_work_experience')
    op.drop_table('citizen_physical_standards')
    op.drop_table('citizen_languages')
    op.drop_table('citizen_family_members')
    op.drop_table('citizen_education')
    op.drop_table('citizen_addresses')
    op.drop_table('applications')
    op.drop_index(op.f('ix_service_catalog_service_code'), table_name='service_catalog')
    op.drop_table('service_catalog')
    op.drop_index(op.f('ix_roles_role_code'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_offices_office_code'), table_name='offices')
    op.drop_table('offices')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_citizens_aadhaar_hash'), table_name='citizens')
    op.drop_table('citizens')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
